# 当修改文件时重新生成站点
auto: true

# 代码高亮
highlighter: rouge

# markdown 渲染引擎
markdown: kramdown

# 永久链接 文章Title
permalink: /:categories/:title/

# 相对永久链接
relative_permalinks: false

# http://zh.wikipedia.org/wiki/Atom_(標準)
feed: /atom.xml

# 站点标题
title: 就是折腾

# 站点地址
url: http://blog.imr3.com

# 站点作者
author:
  name: mr3
  email: mr3.sole@gmail.com
