# 当修改文件时重新生成站点
auto: true

# 代码高亮
pygments: true

# markdown 渲染引擎 rdiscount 不实用maruku 是因为看到有人说 性能略差切对中文支持不佳
markdown: rdiscount

# 永久链接 文章TItle
permallink: /:categories/:title/

# http://zh.wikipedia.org/wiki/Atom_(標準)
feed: /atom.xml

# 站点标题
title: 就是折腾

# 站点地址
url: blog.imr3.com

# 站点作者
author: mr3
